/****** Object:  Table [dbo].[MasterSetup]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MasterSetup](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AllowInputDateFrom] [date] NOT NULL,
	[AllowInputDateTo] [date] NOT NULL,
	[AllowInputInvoiceDateFrom] [date] NOT NULL,
	[AllowInputInvoiceDateTo] [date] NOT NULL,
	[MinimumPasswordLength] [int] NOT NULL,
	[IsPrApprovalProcess] [bit] NOT NULL,
	[IsPoApprovalProcess] [bit] NOT NULL,
	[PrAttachmentFilePath] [varchar](100) NULL,
	[PoAttachmentFilePath] [varchar](100) NULL,
	[IsAllowShortReceivingInventory] [bit] NOT NULL,
	[IsAllowExcessReceivingInventory] [bit] NOT NULL,
	[IsMandatoryBudget] [bit] NOT NULL,
	[PurchaseHistoryLimit] [numeric](2, 0) NOT NULL,
	[PRDefaultText] [nvarchar](200) NULL,
	[PODefaultText] [nvarchar](200) NULL,
	[PRApproverName] [nvarchar](30) NULL,
	[PRApproverPosition] [nvarchar](30) NULL,
	[POApproverName] [nvarchar](30) NULL,
	[POApproverPosition] [nvarchar](30) NULL,
	[DefaultTextOfPoMail] [nvarchar](1500) NULL,
	[EnumReceivingQtyId] [int] NOT NULL,
	[QuotationAttachmentFilePath] [varchar](100) NULL,
	[CoAttachmentFilePath] [varchar](100) NULL,
	[DoAttachmentFilePath] [varchar](100) NULL,
	[IsAllowExcessShippingInventory] [bit] NOT NULL,
	[IsAllowShortShippingInventory] [bit] NOT NULL,
	[SalesHistoryLimit] [numeric](2, 0) NOT NULL,
	[InvoiceApproverName] [nvarchar](30) NULL,
	[InvoiceApproverPosition] [nvarchar](30) NULL,
	[OrderManagementAttachmentFilePath] [varchar](100) NULL,
	[AcceptanceStatementAttachmentFilePath] [varchar](100) NULL,
	[IsAllowMinusInventory] [bit] NOT NULL,
	[InventoryHistoryLimit] [numeric](2, 0) NOT NULL,
	[IsLotControl] [bit] NOT NULL,
	[EnumTypeOfProductionId] [int] NULL,
	[NumberOfDefaultDisplayRecords] [int] NOT NULL,
	[BusinessTripAttachmentFilePath] [varchar](100) NULL,
	[IsPurchaseInsp] [bit] NOT NULL,
	[IsCustomerInsp] [bit] NOT NULL,
	[IsInvoiceDetailEditable] [bit] NOT NULL,
	[CustomerRequirementFilePath] [varchar](100) NULL,
	[DefaultTextOfSalesInvoiceMail] [nvarchar](1500) NULL,
	[SalesInvoiceAttachmentFilePath] [varchar](100) NULL,
	[IsSqApprovalProcess] [bit] NOT NULL,
	[SupplyShippingFilePath] [varchar](100) NULL,
	[SupplyInspectionAttachmentFilePath] [varchar](100) NULL,
	[SupplyOrderAttachmentFilePath] [varchar](100) NULL,
	[MfgOrderAttachmentFilePath] [varchar](100) NULL,
	[IsMfgApprovalProcess] [bit] NOT NULL,
	[MfgIssueOrderHistoryLimit] [numeric](2, 0) NOT NULL,
	[IsPurchaseInvoiceDetailEditable] [bit] NOT NULL,
	[Email] [varchar](100) NULL,
	[Password] [nvarchar](max) NULL,
	[DisplayName] [nvarchar](50) NULL,
	[EmailForSales] [varchar](100) NULL,
	[SalesPassword] [nvarchar](max) NULL,
	[DisplayNameForSales] [nvarchar](50) NULL,
	[EmailForPurchase] [varchar](100) NULL,
	[PurchasePassword] [nvarchar](max) NULL,
	[DisplayNameForPurchase] [nvarchar](50) NULL,
	[PortNo] [int] NOT NULL,
	[Host] [varchar](100) NULL,
	[EnableSsl] [bit] NOT NULL,
	[AvailableStockInquiryLimit] [numeric](2, 0) NOT NULL,
	[IsAccHeaderAndGroup] [bit] NOT NULL,
	[SupplyHistoryLimit] [numeric](2, 0) NOT NULL,
	[FileMakerAttachmentFilePath] [varchar](150) NULL,
	[IsBusinessTripApprovalProcess] [bit] NOT NULL,
	[IsLabelControl] [bit] NOT NULL,
	[ScheduleHistoryLimit] [numeric](2, 0) NOT NULL,
	[DefaultRateOfProjectBudget] [numeric](3, 2) NOT NULL,
	[CreatedUser] [nvarchar](80) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedUser] [nvarchar](80) NULL,
	[ModifiedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_MasterSetup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[MasterSetup] ADD  CONSTRAINT [DF__MasterSet__Creat__19EAC663]  DEFAULT ('ADMIN') FOR [CreatedUser]
ALTER TABLE [dbo].[MasterSetup] ADD  CONSTRAINT [DF__MasterSet__Creat__1ADEEA9C]  DEFAULT ('2013-05-15 15:08:13.100') FOR [CreatedDate]
ALTER TABLE [dbo].[MasterSetup] ADD  CONSTRAINT [DF__MasterSet__Modif__1BD30ED5]  DEFAULT ('ADMIN') FOR [ModifiedUser]
ALTER TABLE [dbo].[MasterSetup] ADD  CONSTRAINT [DF__MasterSet__Modif__1CC7330E]  DEFAULT ('2013-05-15 15:08:13.100') FOR [ModifiedDate]
